services:
    qimnet.solr.client:
        class: SolrClient
        arguments: [ %qimnet.solr.client.options% ]
        
    qimnet.solr.indexer:
        class: Qimnet\SolrClientBundle\Doctrine\Indexer
        arguments: 
            - '@qimnet.solr.client'
            - '@annotation_reader'
            - '@property_accessor'
            - %qimnet.solr.entities%
            
    qimnet.solr.indexable:
        class: Qimnet\SolrClientBundle\Doctrine\IndexableListener
        arguments: [ '@qimnet.solr.indexer' ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }